version: '3'
services:
  ftxx:
    image: warmworm/ftxx-server:1.0.0
    links:
    - mongo
    ports:
    - 8080:3000
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DBNAME: "ftxx"
  wechat:
    image: warmworm/ftxx-wechat:1.0.0
    links:
    - mongo
    ports:
    - 8081:8080
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DBNAME: "ftxx"
  mongo:
    image: mongo:4.0.1-xenial
    restart: always
    ports:
    - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "ftxx"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
